### ISSUE TITLE
[0.0.5] Hoppers don't output items when using Remote Interface

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/RemoteIO#105]
You can pull items using an item pipe from most mods, but Hoppers don't seem to work

https://u.pomf.is/okyiep.png

Is this intended for a block itself to be unable to push things out, but other blocks can pull things from it?

**Comment by dmillerw** [comment]
It's unintentionally intentional. The Remote Interface tries to mimick as much of the block as it can, but the real block doesn't know about anything except itself. So as far as its concerned, there is no chest

**Comment by SPMoo66** [comment]
Ah, I see. Thanks for the clarification.
