### ISSUE TITLE
No IO block connection

### ISSUE THREAD

**Issue by blockbreaker1361** [dmillerw/RemoteIO#13]
When I try to link an IO Block to a vanilla furnace or any other inventory block, it links for 2 seconds and then quickly un-links. I have it within 8 blocks and have the item upgrade and side awareness upgrade as well. I'm feeding it off of a chest with the item ducts from TE and have the filters set up to whitelist the ores I want smelted. The ducts are wrenched in the proper direction and still no connection and no extraction. Help please.

**Comment by dmillerw** [comment]
Couple others have already reported this, but I'm having trouble
replicating it. I'll do more investigating when I can.

**Comment by blockbreaker1361** [comment]
I just wanted to update  you on the progress I have made in my investigation. I have been doing some extensive testing with the IO block and the Sided Proxy block. The IO block, regardless of upgrades WILL NOT connect in any way to a vanilla furnace. The Sided Proxy will. The IO block does connect to any other machines/inventory blocks in vanilla and other mods. The vanilla furnace, for some reason or another, is acting derpy. Usually when you shift+click coal/charcoal and any ores into it, they are supposed to go into their respective spots. The coal/charcoal is going into the top slot. It even does this in unmodded, vanilla Minecraft. So, this is not the mod causing the problem. This is Mojang's fix.
