### ISSUE TITLE
Server Connection Crash

### ISSUE THREAD

**Issue by DarkEspeon** [dmillerw/RemoteIO#18]
I get this error log most everytime as soon as I connect, as well as on of my friends. Is there any fix or is this a problem on your side. This only started when I crashed using another mod block, but only your mod is listed in the log. Every now and then i don't crash, but most times i do and it doesn't stop for about 1-3 hours depending. Also, this doesn't happen in singleplayer.

Thanks, DarkEspeon

Error Log: http://pastebin.com/bijK3UyU

**Comment by dmillerw** [comment]
My mod is showing up, but it's not the cause of the crash.
