### ISSUE TITLE
IO Block Crash

### ISSUE THREAD

**Issue by the-creamster** [dmillerw/RemoteIO#26]
Whenever a IO Block is placed in the world, it crashes the server(single player & presumably multiplayer); am using the latest 1.7 build. This was discovered when a fellow player went to test something in singleplayer and got an immediate crash; not even going to attempt to do it on the multiplayer server as the same thing will most likely happen.

**Comment by dmillerw** [comment]
Could use the complete log

**Comment by the-creamster** [comment]
Happens with the Remote Inventory & Interface http://pastie.org/9315179; and i can confirm that it prevents the world from being loaded when its been placed in a loaded chunk. Also to note is that the pack doesn't include BC5,IC2 & Railcraft.
