### ISSUE TITLE
[1.7.2] Crash when interacting with Extra Utils Transfer Node (Liquid)

### ISSUE THREAD

**Issue by Dyonovan** [dmillerw/RemoteIO#29]
Using RemoteIO 1.0.7-b22

http://pastebin.com/nRvVuNYW

I have a Remote Interface connected to an Extra Utils Transfer Node liquid.

When I clicked the Location Chip on the Interface, crashed all clients in the area.

It made the area unable to be used. Had to world edit out the block to be able to log back in

**Comment by the-creamster** [comment]
This also occurs when remotely putting items into a crystal chest that come from another remote interface; but i didn't do it so i don't have the crash report.

**Comment by dmillerw** [comment]
Fixed
