### ISSUE TITLE
Crash when EnderIO Item Conduit placed next to linked Remote Interface

### ISSUE THREAD

**Issue by rux616** [dmillerw/RemoteIO#31]
- Place a Remote Interface
- Link it with a chest via Location Chip
- Attempt to place EnderIO Item Conduit
- Crash and burn

Crash log: http://pastebin.com/4LZ0PCcJ

Minecraft 1.7.10
Forge 10.13.0.1187
RemoteIO 1.1.1 b26

**Comment by rux616** [comment]
Also happens when using Refined Relocation.

Crash log: http://pastebin.com/LyBD90jV

**Comment by dmillerw** [comment]
Probably fixed
