### ISSUE TITLE
Remote access issue

### ISSUE THREAD

**Issue by alpharou** [dmillerw/RemoteIO#33]
You can't open remotely the interface of a block from more to 7/8 blocks. Is this intentional?

**Comment by dmillerw** [comment]
Fixed

**Comment by alpharou** [comment]
i don't think so, at least in the latest version 1.3.1 it's range limited. I made a video because it's interesting how it works: http://youtu.be/4Tp0iU0vGos

Maybe there's a mod conflict...

**Comment by dmillerw** [comment]
Ahh, my mistake. Try 1.3.3, and let me know

**Comment by alpharou** [comment]
I'm VERY impressed, you're a very active modder.

I'll test that later...

Remember I owe you a review... I'm working on that too. :D

**Comment by alpharou** [comment]
Well... in v 1.4.0 is not working... It does the same thing... This should be very difficult to fix... maybe you should remove it from the game until you find a way to fix it?

**Comment by dmillerw** [comment]
I'll have to take another look at it. In the mean time, you can craft a wireless transmitter, and link that to the IO block.

**Comment by alpharou** [comment]
The wireless transmitter works very well! But it doubles and fails in a weird way when you access it from another dimension, for example, I can't access the block in the nether from the Overworld (even ForceLoading the chunk), but if you're in the same dimension you shouldn't have any problem at all.

**Comment by dmillerw** [comment]
You aren't able to access blocks from another dimension? 'cause that's intentional

**Comment by alpharou** [comment]
But you can mess up with that opening and closing your inventory to duplicate transmitters and randomly you will have access to the items in the block... it's weird because you will see that items randomly in your inventory and you can drop it and... yeah, they aren't visual bugs, the items are dropped for real and transfered from the far away block directly onto the ground.

**Comment by dmillerw** [comment]
Ohhh... hmm. What are you trying to remotely access?

**Comment by alpharou** [comment]
an enervation dynamo from thermal expansion. I can make a quick video about that and give you the link.

**Comment by dmillerw** [comment]
That'd be great

**Comment by alpharou** [comment]
Oh WoW, will the remote interface self chunkload or something like that? because I can access the block itself from far away.

**Comment by alpharou** [comment]
The video is uploading... http://youtu.be/G1oJOg8zJF0

**Comment by dmillerw** [comment]
Huh...

**Comment by alpharou** [comment]
Yeah... The remote access is very unstable... it crashes sometimes if you access blocks from too far away. If the chunk is force loaded or not doesn't matter. Thermal Expansion machines are more unstable than the other in general because they grant you access but the GUI is missing, then your inventory gets messy and you need to quit and enter again to solve the sync problem.

**Comment by dmillerw** [comment]
Unfortunately, not much I can do about that. The feature itself is a hack

**Comment by alpharou** [comment]
I told you, I don't care if you remove it from the mod. It's still awesome.
