### ISSUE TITLE
Remote interface range issue?

### ISSUE THREAD

**Issue by shadowsyllvet** [dmillerw/RemoteIO#36]
The remote interface upgrade only works if the player is within access range of the interface being accessed. Upgrade is only useful in situations where the interface is behind a wall/in the middle of complicated piping etc. the player, not the remote interface has to be within 7 blocks of a minecraft chest., at which point they could just open the chest themselves. Is this intentional?

**Comment by shadowsyllvet** [comment]
I just saw the changelog for an earlier release, so I'm thinking this was intentional. I also saw mention of range upgrades in the forum post. Is the range locked at 8 blocks? Can it be extended/upgraded? If it can(presently), how? If it's a future release feature, no biggie, I can wait.

**Comment by dmillerw** [comment]
That's actually not intentional, at least not until the range stuff is implemented. Fixing now.
