### ISSUE TITLE
Crash Report:  java.lang.NoClassDefFoundError: dmillerw/remoteio/tile/TileRemoteInterface

### ISSUE THREAD

**Issue by SnowShock35** [dmillerw/RemoteIO#38]
Hey Dylan,

Tried adding RemoteIO to my pack I had to remove  the ic2 api due to a bug with mekanism atm but its saying there is saying "java.lang.NoClassDefFoundError: dmillerw/remoteio/tile/TileRemoteInterface" Even though its there when I looked. See http://goo.gl/JhQMei so whats up with that does it rely on something in the ic2 api or is it a bug with the version?

Let us know when you can. Thanks
-Snow ;)

**Comment by dmillerw** [comment]
That's really weird... I'll take a look when I can.

**Comment by SnowShock35** [comment]
Thanks ;) and when you get it fixed i will re add it to the pack.

**Comment by dmillerw** [comment]
**Hopefully** fixed in 1.3.0, but I'll leave this open. If you could test, that'd be great!

**Comment by dmillerw** [comment]
Alright, hopefully fixed in 1.3.1 this time!
