### ISSUE TITLE
Thaumcraft 4 missing

### ISSUE THREAD

**Issue by alpharou** [dmillerw/RemoteIO#40]
It seems to want thaumcraft 4 api's to work, because my saved world crashes once i try to transfer liquids, and i can't open that world without having an inminent crash. v 1.3.3

Pastebin crash: http://pastebin.com/eFSpzEA5

**Comment by dmillerw** [comment]
Crash report please

**Comment by alpharou** [comment]
edited the issue with the crash report.

**Comment by alpharou** [comment]
Great!
