### ISSUE TITLE
Easy crafting

### ISSUE THREAD

**Issue by alpharou** [dmillerw/RemoteIO#41]
Well... This mod is AWESOME, and the possibilities are endless, but... the crafting is so easy! I mean... only a few enderpearls, sticks, redstone and gold and you are done!

The crafting should be a lot more difficult to do all the thing. because all the remote connections and liquid transportation, energy transfer, items flowing instantly from your other base one million blocks away! I think this mod is OP right now...

This should work: do the crafting more difficult and expensive and request power in the interface or wathever depending on the distance traveled.

**Comment by dmillerw** [comment]
I tried having a power requirement once, and people exploded with hate

**Comment by alpharou** [comment]
Well, that was because the other people only wants op things easily... It's up to you. Balancing the mod or leaving it intact. I think this mod is extremely overpowered. Not only the crafting, but everything. 

One thing you can do is al least change the crafting to something more complicated and elaborated, because a remote interface should be a very expensive but brilliant block, not only a block of gold surrounded by Redstone and an ender pearl... 

And think about that... If you balance it, the mod reputation will increase a lot because the best gamers will use it and they will be obfuscated because it's really a brilliant mod.
