### ISSUE TITLE
temporal crafting issue

### ISSUE THREAD

**Issue by alpharou** [dmillerw/RemoteIO#44]
You can't craft RF transfer chip if the energy duct isn't in the game. You could replace that with conductance coils.

**Comment by dmillerw** [comment]
It should just require Redstone

**Comment by alpharou** [comment]
No, I can't craft it with redstone.

**Comment by dmillerw** [comment]
Hmm, alright

**Comment by alpharou** [comment]
Wait! I'm using an outdated version.

**Comment by alpharou** [comment]
Anyway, I can't craft it.
