### ISSUE TITLE
Server Crash - Remote Inventory with AE2 involved

### ISSUE THREAD

**Issue by ruyanve** [dmillerw/RemoteIO#46]
Hey man, don't know if this is on your end or Applied Energistics just letting you know...

Server crash

Forge 1217, Appeng rv2 beta 4, RemoteIO 1.4.3B49

http://pastebin.com/XYnXw6QZ

Happens whenever I link a remote inventory to a chest and have AE2 export stuff in it. 
Sorry if this is purely AE2 related!

**Comment by dmillerw** [comment]
That's really weird. I could've sworn I fixed this... :/

**Comment by ruyanve** [comment]
Well... you did! They somehow managed to break it again in their latest release. I was "forced" to update to the newest version and kablaam... crashy crashy long time, had to remove RIO to be able to log in again. Of course it's back on the server, can't live without it.
