### ISSUE TITLE
Items become "Unnamed" after shift-right-clicking.

### ISSUE THREAD

**Issue by maxpowa** [dmillerw/RemoteIO#49]
So far the items affected by this appear to be the location chip and the wireless transmitter. If you rename them, they do not show the new name, just "Unnamed". I've checked the NBT tags after renaming and the display tag is definitely there, so it's not that the NBT isn't applying.

http://puu.sh/c9JyU/0903817000.jpg

**Comment by Ganjalf-Amsterdoom** [comment]
This is still happening to me in latest version, on a server I placed a thermal expansion leadstone fluxduct beside a remote interface, I got kicked off the server, I logged back in and all the RemoteIO items I had in inventory became "unnamed".
