### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by ZeekDaGeek** [dmillerw/RemoteIO#50]
I created a system to automatically pull items out of a remotely accessed chest and put the items into auto activators using Steve's Factory Managers. It worked completely fine until the world was reloaded then it started to crash.

The following is the crash log: http://pastebin.com/Cwj383Mj

I used an NBT Editor to remove the Remote Interface and the world loaded properly. I replaced the interface with the chest exactly as it was with the Remote Interface and it worked perfectly fine, which leads me to think that it's related to the interface in some way.

**Comment by dmillerw** [comment]
Hopefully fixed in latest commit. Leaving this open until confirmed though.

**Comment by ZeekDaGeek** [comment]
Seems to be working without a crash.
