### ISSUE TITLE
Breaking Remote Interface crashes game

### ISSUE THREAD

**Issue by ZeekDaGeek** [dmillerw/RemoteIO#62]
Forge version: 10.13.2.1236
Mod version: RemoteIO-1.7.10-1.7.1.B80-universal.jar
Other mods: http://tinyurl.com/wwpack

Crash log: http://pastebin.com/pQhbvu7r

When attempting to break a remote IO the game appears to crash.

Sidenote: I had mentioned to you on Twitter that essentia phials weren't working. They are, I had forgotten the remote access upgrade for those.

**Comment by dmillerw** [comment]
This _might_ be an issue with TC. I can't reproduce it.

**Comment by ZeekDaGeek** [comment]
I attempted to mine using an Iron pickaxe, I still crashed but this time with this error.

Crash log: http://pastebin.com/8GMCWh2Y

Don't know if that helps any.
