### ISSUE TITLE
[Enhancement] Blank location cards don't stack

### ISSUE THREAD

**Issue by ZeekDaGeek** [dmillerw/RemoteIO#65]
SUGGESTION / ENHANCEMENT

Seeing as location cards are part of crafting recipes it seems odd that blank cards don't seem to stack with each other. I've recently been crafting a large number of location cards for large amounts of essentia upgrades, remote camouflage upgrades, etc. It's very inconvenient to try to craft when they dont stack and they end up taking up a large amount of space if you need to store them.

If such a feature was implemented  it seems like the ability to craft them in your inventory to reset them to blank would be very helpful.

**Comment by dmillerw** [comment]
Added
