### ISSUE TITLE
[Enhancement] Wrench support

### ISSUE THREAD

**Issue by ZeekDaGeek** [dmillerw/RemoteIO#66]
SUGGESTION / ENHANCEMENT

An additional tool seems a little cumbersome to carry around. It seems like a shift click with a wrench should be able to open the interface and a simple right click should be able to rotate the camouflaged block.

If not the normal wrench maybe just something like the OmniWrench from Redstone Arsonal.

**Comment by dmillerw** [comment]
aaaaaaand added :)
