### ISSUE TITLE
Redstone signal offset by 1(see link for images)

### ISSUE THREAD

**Issue by shadowsyllvet** [dmillerw/RemoteIO#67]
https://github.com/BuildCraft/BuildCraft/issues/2301#issuecomment-66868890

**Comment by shadowsyllvet** [comment]
@dmillerw Were you able to reproduce this?

**Comment by riseon** [comment]
This was happening to me, as well.  I'm using the latest Buildcraft.  in addition placing a remote interface in world made the save unloadable.  I had to remove it with mcedit.

Console log.  https://paste.ee/p/KwTfS
