### ISSUE TITLE
getFlags overflow

### ISSUE THREAD

**Issue by ZeekDaGeek** [dmillerw/RemoteIO#69]
Forge: 10.13.2.1277
Mod version: remoteio-1.7.10-1.8.1.b84-universal
Other mods: http://tinyurl.com/wwpack

http://pastebin.com/LrWb1FvN

Not exactly sure why this one is crashing crazy... Maybe you'll get something out of this?

**Comment by Zero9o1o** [comment]
The way this crashed happen was you take two remote interfaces and place them both down. Then you take 2 AE2 transfer cards and put one in each interface. Then get a location card and store the location of one of them, then try to like it to the other one.

**Comment by dmillerw** [comment]
Uhh, you're linking blocks to each other, so that they each reference the other. How did you expect this _not_ to crash? Don't do this.

**Comment by ZeekDaGeek** [comment]
Well this seems like a major problem still... You're basically saying "Oh well don't put my mod on a server because anyone can use it to corrupt the world, making it completely unable to load, if they're being malicious or are curious about linking two things together"

Isn't there a way to say

if (Block.getByLocation(linkCardX, linkCardY, linkCardZ) == remoteInterfact) { return false and make me flash orange instead of crashing everything? }
