### ISSUE TITLE
AE2 Remote access is a bit bugged

### ISSUE THREAD

**Issue by LuciCMD** [dmillerw/RemoteIO#71]
Sometimes trying to connect to an AE system via the remote interface your client mat crash due to an inventory loading error.

**Comment by dmillerw** [comment]
Uh, what?

**Comment by LuciCMD** [comment]
If you use a location card to set a target, load it on an interface, and put camo, access and item upgrades in(remote that is) it has the possibility of crashing your client, mainly at long distances.  It has worked for me before, although.

**Comment by dmillerw** [comment]
Could I get a crash log?

**Comment by LuciCMD** [comment]
http://pastebin.com/V6RqEPn4

**Comment by LuciCMD** [comment]
The last time I used it, the AE2 network card was also broken-sorry if this is a repeat haven't read all of the issues
