### ISSUE TITLE
StackOverFlow On Server Start

### ISSUE THREAD

**Issue by LokeYourC3PH** [dmillerw/RemoteIO#77]
So, i am getting this when starting my server:

https://gist.github.com/Yanniclord/00700636b92e1f35fdbe

**Comment by LokeYourC3PH** [comment]
Gives everyone a timeout upon joining. I knew i could find something that would make RemoteIO necessary to be removed from the server. I remember i had this before, but never reported it.

**Comment by LokeYourC3PH** [comment]
This is EXACTLY what i mean by RIO support. You make your own conclusions.

**Comment by dmillerw** [comment]
https://github.com/Slikrick/RemoteIO
