### ISSUE TITLE
[1.10.2][0.1-ALPHA] Crash on startup

### ISSUE THREAD

**Issue by Rosethorns** [dmillerw/RemoteIO#81]
Crashlog:
http://pastebin.com/v57bX8iV

Forge version:
1.10.2-12.18.1.2095
1.10.2-12.18.1.2094
1.10.2-12.18.1.2054

Other Mods:
None

**Comment by dmillerw** [comment]
Can't seem to reproduce this. I've tried a new build of RemoteIO, the version currently available on CurseForge, along with all three Forge versions listed

**Comment by dmillerw** [comment]
Ahh, I think I see the issue. The widget on the MCF page hasn't updated to reflect the version for 1.10. I tested the old 1.7 version and got the same crash

Grab it direct from CurseForge for now
