### ISSUE TITLE
[0.0.1] Pocket Gadget doesn't save frequency?

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/RemoteIO#82]
I don't seem to be able to get the Pocket Gadget to save a frequency, when I can get the Block Analyzer and Remote Interface to work just by accessing the menu, changing the frequency, and pressing escape. When I try to do the same with the Pocket Gadget, it always resets to 0.
Is there a confirmation key I'm supposed to press or something?

**Comment by dmillerw** [comment]
Fixed in next release, to be released later today

**Comment by SPMoo66** [comment]
Cool, thanks!

**Comment by SPMoo66** [comment]
It still isn't saving frequency as of [0.0.3]
