### ISSUE TITLE
[0.0.3] Odds and ends visual issues

### ISSUE THREAD

**Issue by SPMoo66** [dmillerw/RemoteIO#87]
Just some minor visual things to report here-

Stencil Table, Part Builder, Tool Forge from Tinkers' Construct don't keep their wood/metal type visuals
https://u.pomf.is/axtjlp.png

Vanilla's Cobblestone Walls are invisible, alongside any other modded walls
https://u.pomf.is/vkqggc.png

Tinkers' Construct patterns don't render on tables, similar thing with drying racks
https://u.pomf.is/vbrltt.png

Storage Drawers don't keep their orientation (visually only) or wood type and don't show the item within, but you can input items into the side which should be the correct orientation. (If the drawer faces North, it always renders East facing, but accepts items from the North side.)
You also don't seem to be able to withdraw items from the drawer, so I guess that's another problem (you might be able to, but you break the block instantly).
https://u.pomf.is/kncebi.png

Grass and leaves render in gray
https://u.pomf.is/cjvpuv.png

Signs render inside a blue version of the Remote Interface (same thing with mob heads)
https://u.pomf.is/pjgtvr.png

Terrestrial Agglomeration Plate from Botania renders only partially
https://u.pomf.is/oembgk.png

Dialing Device from EnderIO renders upside-down...? (also always East-facing)
https://u.pomf.is/cdhqpp.png
Wooden Wall Mount from Immersive Engineering also seems to do this

Sorry for spamming you with issues, just want to help out. This really looks like a mod I'd like to include eventually :)

**Comment by dmillerw** [comment]
I've split this into multiple issues so I can track work on them better. Closing this one

I appreciate all the bug reports! :)

**Comment by SPMoo66** [comment]
I just want to say that everything looks good so far! I haven't encountered any real visual bugs outside the expected strange multiblocks from certain mods.

One issue I've seen so far is that you have correctly added left click functionality (in the case of storage drawers), but the block still breaks immediately and doesn't drop itself. Not sure if you wanted to change that quite yet.

**Comment by dmillerw** [comment]
I'll have to do some additional testing
